routes/web.php
<?php

use App\Http\Controllers\admin\BlogCategoryController;
use App\Http\Controllers\admin\BlogController;
use App\Http\Controllers\PageController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', [PageController::class, 'home'])->name('public.home');
Route::get('/contact', [PageController::class, 'contact'])->name('public.contact');
Route::get('/news', [PageController::class, 'news'])->name('public.news');
Route::get('news/category/{category}', [PageController::class, 'news'])->name('public.newsByCategory');

Route::get('/news/{news}', [PageController::class, 'newsDetail'])->name('public.newsDetail');

Route::prefix('admin-panel')->group(function () {
    //Blog
    Route::get('/blog/', [BlogController::class, 'index'])->name('blog.index');
    Route::get('/blog/create', [BlogController::class, 'create'])->name('blog.create');
    Route::post('/blog', [BlogController::class, 'store'])->name('blog.store');
    Route::get('/blog/{blog}/edit', [BlogController::class, 'edit'])->name('blog.edit');
    Route::put('/blog/{blog}', [BlogController::class, 'update'])->name('blog.update');
    Route::delete('/blog/{blog}', [BlogController::class, 'destroy'])->name('blog.destroy');

    //BlogCategory
    Route::resource('blog-category', BlogCategoryController::class);
});







Route::group(['prefix' => 'admin'], function () {
    Voyager::routes();
});

app/Models/BlogCategory.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class BlogCategory extends Model
{
    use HasFactory;
}

app/Http/Controllers/admin/BlogCategoryController.php
<?php

namespace App\Http\Controllers\admin;

use App\Http\Controllers\Controller;
use App\Models\BlogCategory;
use Illuminate\Http\Request;

class BlogCategoryController extends Controller
{
    /**
     * Display a list of Blogs categories.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $pageTitle = 'Admin Blog Categories';
        $pageActive = 'blogCategoryPage';
        $blogCategories = BlogCategory::paginate(10);

        return view('admin.blog-category.index', compact('pageActive', 'pageTitle', 'blogCategories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data = [
            'pageTitle' => 'Admin create Blog Categories',
            'pageActive' => 'blogCategoryPage'
        ];

        return view('admin.blog-category.form', $data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required|min:3|max:50',
        ]);

        $blogCategory = new BlogCategory();
        $blogCategory->name = $request->name;

        if ($blogCategory->save()) {
            return redirect()
                ->route('blog-category.index')
                ->with(['success' => __('blog-category.success_store')]);

        } else {
            return back()
                ->withErrors(['msg' => __('message.request_error')])
                ->withInput();
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(int $id)
    {
        $pageTitle = 'Admin create Blog Categories';
        $pageActive = 'blogCategoryPage';
        $record = BlogCategory::findOrFail($id);

        return view('admin.blog-category.form', compact('pageTitle', 'pageActive', 'record'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     * @return \Illuminate\Http\Response
     * @throws \Illuminate\Validation\ValidationException
     */
    public function update(Request $request, int $id)
    {
        $this->validate($request, [
            'name' => 'required|min:3|max:50',
        ]);

        $blogCategory = BlogCategory::findOrFail($id);
        $blogCategory->name = $request->name;

        if ($blogCategory->save()) {
            return redirect()
                ->route('blog-category.index')
                ->with(['success' => __('blog-category.success_update')]);

        } else {
            return back()
                ->withErrors(['msg' => __('message.request_error')])
                ->withInput();
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(int $id)
    {
        $blogCategory = BlogCategory::findOrFail($id);

        if ($blogCategory->delete()) {
            return redirect()
                ->route('blog-category.index')
                ->with(['success' => __('blog-category.success_delete')]);

        } else {
            return back()
                ->withErrors(['msg' => __('message.request_error')])
                ->withInput();
        }
    }
}

resources/views/admin/blog-category/form.blade.php
@extends('layouts.admin')

@section('main')
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Blog categories</h1>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <!-- left column -->
                <div class="col-md-12">
                    @include('admin.components.error-message')

                    <!-- general form elements -->
                    <div class="card card-primary">

                        <div class="card-header">
                            <h3 class="card-title">{{ !empty($record) ? 'Edit' : 'Add' }} category</h3>
                        </div>
                        <!-- /.card-header -->
                        <!-- form start -->
                        <form id="category-form" action="{{ !empty($record) ? route('blog-category.update', $record->id) : route('blog-category.store') }}" method="post">
                            {{ csrf_field() }}

                            @if (!empty($record))
                                {{ method_field('PUT') }}
                            @endif

                            <div class="card-body">
                                <div class="form-group">
                                    <label for="name">Name</label>
                                    <input type="text" class="form-control" id="name" name="name" value="{{ old('name', !empty($record->name) ? $record->name : '') }}" placeholder="Name:">
                                </div>
                            </div>
                            <!-- /.card-body -->

                            <div class="card-footer">
                                <button type="submit" class="btn btn-primary">Submit</button>
                            </div>
                        </form>
                    </div>
                    <!-- /.card -->
                </div>
                <!-- /.row -->
            </div><!-- /.container-fluid -->
        </div>
    </section>

@endsection

resources/views/admin/blog-category/index.blade.php
@extends('layouts.admin')

@section('styles')
    <!-- DataTables -->
    <link rel="stylesheet" href="{{ asset('plugins/datatables-bs4/css/dataTables.bootstrap4.min.css') }}">
    <link rel="stylesheet" href="{{ asset('plugins/datatables-responsive/css/responsive.bootstrap4.min.css') }}">
@endsection

@section('main')
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Blog categories</h1>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                    @include('admin.components.success-message')
                    @include('admin.components.error-message')

                    <div class="card">
                        <div class="card-header">
                            <h3 class="card-title">List of all categories</h3>
                            <div class="card-tools">
                                <a href="{{ route('blog-category.create') }}" class="btn btn-success"><i class="fas fa-plus"></i> Add category</a>
                            </div>
                        </div>
                        <!-- /.card-header -->
                        <div class="card-body">
                            <div class="dataTables_wrapper dt-bootstrap4">
                                <div class="row">
                                    <div class="col-sm-12">
                                        <table class="table table-bordered table-striped dataTable dtr-inline">
                                            <thead>
                                            <tr>
                                                <th>Name</th>
                                                <th width="150px">Date add</th>
                                                <th width="200px">Actions</th>
                                            </tr>
                                            </thead>

                                            <tbody>
                                            @foreach ($blogCategories as $category)
                                                <tr>
                                                    <td>{{ $category->name }}</td>
                                                    <td>{{ $category->created_at }}</td>
                                                    <td>
                                                        <a href="{{ route('blog-category.edit', $category->id) }}" class="btn btn-primary">
                                                            <i class="fas fa-edit"></i> Edit
                                                        </a>
                                                        <form action="{{ route('blog-category.destroy', $category->id) }}" method="post" style="display: inline">
                                                            {{ csrf_field() }}
                                                            {{ method_field('DELETE') }}
                                                            <button class="btn btn-danger" type="submit"><i class="fas fa-trash-alt"></i> Delete</button>
                                                        </form>
                                                    </td>
                                                </tr>
                                            @endforeach

                                            </tbody>
                                            <tfoot>
                                            <tr>
                                                <th>Name</th>
                                                <th>Date add</th>
                                                <th>Actions</th>
                                            </tr>
                                            </tfoot>
                                        </table>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-sm-12 col-md-5">
                                        <div class="dataTables_info">Showing 1 to 10 of 57 entries</div>
                                    </div>
                                    <div class="col-sm-12 col-md-7">
                                        {{ $blogCategories->links('admin.components.pagination') }}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- /.col -->
                </div>
                <!-- /.row -->
            </div>
            <!-- /.container-fluid -->
        </div>
    </section>

@endsection